mtennoe/swagger-typescript-codegen

lib/typescript.js
This lets the template access the sequence of individual enum values, and not just the string literal union type.
=> Expose the swaggerType.enum values as a sequence in typespec.enum.

lib/typescript.js, templates/type.mustache
1 `Dictionary` is a custom type, let's use typescript built-in type `{ [key: string]: value }`
2 isDictionary is ignored in default templates
=> support built-in dictionary type

templates/method.mustache
This PR adds the possibility to override the request path via `$path` parameter, similar to existing `$domain` parameter.
The path can be overridden by a simple string or by callback (the latter is not possible for `$domain`).
=> Override path

templates/class.mustache, templates/method.mustache
Extract common request options to own exported interface
**Important**: this PR depends on PR #42 (which introduces `$path`)
=> Formalize common request options in generated code

templates/method.mustache
Changes:
* `queryParameters` are ignored if set to `null` or `undefined`, but not for other falsy values (so we detect them as errors)
* uses spread operator to improve readability
=> Improve queryParameter assignment

templates/class.mustache, templates/type.mustache
No newlines between properties of TypeScript interface. Also, separate some types by new lines.
I prettify generated code automatically via `prettier`, and this especially improves the prettified results. @mtennoe are you interested in a PR for such an automatic prettification?
=> Improve whitespace in generated output

templates/type.mustache
*So this one could be controversial, and is backwards-incompatible.*
Currently, when generator encounters an OpenAPI array definition, it generates
```code
element: Array<type> | type
```
This PR removes the optional `| type`.
The reasoning for this could be (I haven't verified this) that the current generator lacks handling of [`oneOf`](https://json-schema.org/understanding-json-schema/reference/combining.html).
But - for my understanding - the PR represents the correct behavior. It also simplifies handling of array elements as we don't always have to handle two code paths in TS when there is just an array.
I don't know if anyone really needs the old, "fuzzy" behavior. If yes, there could be an option for this?
@mtennoe let me know what you think.
**Note**: this PR depends on PR #41
=> Arrays are always arrays

templates/type.mustache
(second try with correct branch)
This repairs the grunt-based tests run with "grunt". The bug occurred in
conjunction with "beautify" option, I think (I never had this bug in my
generated client, because I do not use "beautify" there but a
custom prettification via "prettier")
The other part of the test suite (the jest-based one) will be fixed in next PR.
=> [Bugfix] Missing semicolon after object properties

src/codegen.ts
I'd like to be able to use data from processed swagger spec for custom analysis and, possibly, a different templating engine. For that purpose, it is nice to have a method which returns this data to us.
=> Added method to get data and options from processed swagger spec without generating the code.

__tests__/__snapshots__/runner.js.snap, templates/class.mustache
Fix `@types/superagent` has no default export.
Although this might be an issue with the `"@types/superagent": "^4.1.0"` type definition.
With typescript `"strict": true,` config enabled, doesn't allow implicit any type.
```
TS1192: Module '"C:/_/node_modules/@types/superagent/index"' has no default export.
TS7006: Parameter 'error' implicitly has an 'any' type.
TS7006: Parameter 'response' implicitly has an 'any' type.
```
=> Fix @types/superagent has no default export

src/type-mappers/dictionary.ts, src/typescript.test.ts
Fixes issue parsing NSwag's json spec output format.
Issue with json spec format: "additionalProperties": false
Input:
```
"ProductDetailsViewModel": {
"type": "object",
"additionalProperties": false, // this line
"properties": {
"BrandName": {
"type": "string"
}
}
}
```
Expected output:
object type
Actual output:
dictionary type
=> Fix issue with json spec format: "additionalProperties": false

src/swagger/Swagger.ts, src/view-data/responseType.ts
Hello, I've come across an NPM package and started using it, however I found that the client is not returning right models for anything but 200 respones, so I've spent some time putting together a pull request addressing the issue.
Consider this swagger file example
https://gist.github.com/kettlensk/3bab7c7a94738c27915fd5f7818eee6b
```swagger
paths:
/pet:
post:
summary: "Add a new pet to the store"
operationId: "addPet"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
name: "body"
description: "Pet object that needs to be added to the store"
required: true
schema:
$ref: "#/definitions/Pet"
responses:
201:
description: "Pet Created"
schema:
$ref: "#/definitions/Pet"
405:
description: "Invalid input"
```
An API call will respond with `201 CREATED` …
=> Returning correct model for all 2xx responses

src/type-mappers/object.ts, tests/apis/allOf.json
I noticed that generated code can have duplicate properties in case `allOf` section also includes a reference to an object that has the same properties.
I hope my ad-hoc fix is okay!
Regards,
Andreas
=> Remove duplicate properties from objects

src/getViewForSwagger2.test.ts, src/getViewForSwagger2.ts, src/options/options.test.ts, src/options/options.ts, src/view-data/method.ts, src/view-data/operation.ts, templates/method.mustache
To retain backwards compatibility, deprecated methods are not generated by default.
Fixes #70
=> Add option to generate code for deprecated methods

__tests__/__snapshots__/runner.js.snap, templates/class.mustache
since the generated typescript file is most likely using different style conventions than defined and tweaked in the `tslint` config for the various projects the generated file should be added to it makes sense to disable `tslint`ing that file
=> add `// tslint:disable` to the top of the generated file

__tests__/__snapshots__/runner.js.snap, templates/class.mustache
fix the following issue:
```text
SwaggerTest.ts(432,40): error TS2345: Argument of type '{ default: SuperAgentStatic; agent(): SuperAgentStatic & Request; serialize: { [type: string]: Serializer; }; parse: { [type: string]: Parser; }; jar: CookieJar; attachCookies(req: SuperAgentRequest): void; ... 26 more ...; unsubscribe(url: string, callback?: CallbackHandler | undefined): SuperAgentRequest; }' is not assignable to parameter of type 'SuperAgentStatic'.
Type '{ default: SuperAgentStatic; agent(): SuperAgentStatic & Request; serialize: { [type: string]: Serializer; }; parse: { [type: string]: Parser; }; jar: CookieJar; attachCookies(req: SuperAgentRequest): void; ... 26 more ...; unsubscribe(url: string, callback?: CallbackHandler | undefined): SuperAgentRequest; }' is missing the …
```
=> fix issue with `superagent` initialization

__tests__/__snapshots__/runner.js.snap, templates/class.mustache, templates/method.mustache
* add support for parameterization of `superagent`'s `retry`, `timeout`, and `deadline` parameters via `CommonRequestOptions`
* replace explicitly adding `$queryParameters`, `$domain`, and `$path` for each endpoint impl by using `& CommonRequestOptions` instead
* tighter type checks for `headers` and `query` parameters
* use `req.set(headers)` instead of a loop over all headers and setting them individually
=> several enhancements

__tests__/__snapshots__/runner.js.snap, __tests__/fixtures/responses/swagger.json, __tests__/runner.js, src/getViewForSwagger2.ts, src/view-data/method.ts
* `swagger` supports the definition of shared `responses` objects which can be ref'ed by several endpoints
* see: https://github.com/reverb/swagger-spec/blob/4678d9fbe5723cb926b50fe0d1ae877c34e44a42/schemas/v2.0/schema.json#L81
* in order to deal with this potential additional level of indirection the swagger schema is normalized with respect to the `responses` defs before the existing algorithm is triggered
E.g. sample input schema:
```json
{
"swagger": "2.0",
"info": {
"version": "0.0.1",
"title": "your title"
},
"paths": {
"/persons": {
"get": {
"operationId": "get_person",
"description": "Gets `Person` object.",
"responses": {
"200": { "description": "empty schema" },
"201": {
"description": "inline schema",
"schema": { "type": "object", "properties": { "inline_schema": { "type": …
```
=> add support for shared `responses` defs

README.md, __tests__/__snapshots__/runner.js.snap, __tests__/fixtures/collectionFormat/swagger.json, __tests__/runner.js, src/swagger/Swagger.ts, src/type-mappers/array.ts, src/typescript.test.ts, src/view-data/parameter.ts, templates/class.mustache, templates/method.mustache
Currently, the `collectionFormat` configuration is ignored and all array parameters behave like `"collectionFormat": "multi"`.
```
// example parameter config
{
"name": "csvParam",
"type": "array",
"items": {
"type": "string"
},
"in": "query",
"collectionFormat": "csv"
}
```
Wrong: ?csvParam=foo&csvParam=bar
Correct: ?csvParam=foo,bar
I tried to implement `collectionFormat` and would be happy if it get merged after a review.
https://swagger.io/docs/specification/2-0/describing-parameters/#array-and-multi-value-parameters
=> implemented collection format for query and path array values

src/options/options.ts, src/transform/transformToCodeWithMustache.ts
The properties inside `TemplateLocations` are not locations, it's the full file content.
It would be nice to change it to be file locations, but that would not be very nice for compatibility.
=> Rename 'TemplateLocations' to 'OptionTemplates'

src/codegen.ts, src/generators/codeGenerator.ts, src/generators/swagger2.ts, src/options/options.test.ts, src/options/options.ts
Splitting out the not exported code from codegen.ts to make it easier to read.
There are a few exported methods in `CodeGen` that I don't really see a good use, I didn't want to remove anything for compatibility.
=> Refactor codegen.ts

__tests__/__snapshots__/runner.js.snap, src/view-data/headers.ts, templates/class.mustache
When using `produces` or `consumes` in the swagger description there's currently a case mismatch between the casing of the code generator and superagent.
In my specific case, I have an endpoint consuming `text/csv`. Apparently, the body is of type `string`.
Internally, when sending a string to the endpoint `res.send(body)` is called. In the `send` method, superagent gets the `content-type` header (lower case, [see here](https://github.com/visionmedia/superagent/blob/c7a10e2b51609705936cfcb5bc1bd8a40e8fe1cb/src/request-base.js#L594)).
If it doesn't find it, the content type is overriden and set to `application/x-www-form-urlencoded`. Thus, my string body is sent as `[object Object]` to the backend because the content is transformed. This [happens …
=> Use lower case default headers

__tests__/__snapshots__/runner.js.snap, src/getViewForSwagger2.test.ts, src/type-mappers/object.ts
I fixed an error that caused me some headache, but I still don't think it's completely right now.
If a swagger object has an array of strings as "required" attribute, it will result in a type that has "isRequired" set to true. That doesn't feel right.
=> Fix an error when swagger type is object, but doesn't have the type attribute

src/type-mappers/void.ts
The `object` type in C# outputs a Swagger definition as below:
```json
"Example": {
"type": "object",
"additionalProperties": { }
}
```
`additionalProperties` is then passed to `isVoidType()` and returns true
because all of the checked properties are undefined, and we end up with
e.g. `Dictionary<void>` instead of `Dictionary<{}>`.
=> fix: invalid types such as Dictionary<void> are generated

README.md, src/options/options.ts, src/view-data/method.ts, templates/method.mustache
Closes #124 
Adds an option to disable the behaviour of turning query parameters in a POST request into form data. The default remains to use form data in POST requests.
=> Add option to use query params in POST request
